import fs from 'node:fs/promises';
import path from 'node:path';
import { loadPostsFrontmatter } from './utils';

const MIN_IMAGES = Number(process.env.MIN_IMAGES_PER_POST ?? '3');
const MAX_IMAGES = Number(process.env.MAX_IMAGES_PER_POST ?? '5');

function todayKST() {
  const now = new Date();
  const kst = new Date(now.getTime() + 9 * 60 * 60 * 1000);
  return `${kst.getUTCFullYear()}-${String(kst.getUTCMonth() + 1).padStart(2, '0')}-${String(kst.getUTCDate()).padStart(2, '0')}`;
}

async function exists(filePath: string) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function main() {
  const posts = await loadPostsFrontmatter();
  const today = todayKST();
  const targets = posts.filter((row) => row.data.autoGenerated === true && row.data.publishedAt === today);

  if (targets.length === 0) {
    console.log('no target posts for image validation');
    return;
  }

  const failures: string[] = [];

  for (const row of targets) {
    const slug = String(row.data.slug ?? '');
    if (!slug) continue;

    const markdownMatches = row.body.match(new RegExp(`/assets/posts/${slug}-\\d+\\.png`, 'g')) ?? [];
    const markdownCount = new Set(markdownMatches).size;

    let fileCount = 0;
    for (let i = 1; i <= MAX_IMAGES; i += 1) {
      const filePath = path.join(process.cwd(), 'public/assets/posts', `${slug}-${i}.png`);
      if (await exists(filePath)) fileCount += 1;
    }

    if (markdownCount < MIN_IMAGES || fileCount < MIN_IMAGES) {
      failures.push(`${slug}: markdown=${markdownCount}, files=${fileCount}, expected>=${MIN_IMAGES}`);
    }
  }

  if (failures.length > 0) {
    console.error('post image validation failed');
    for (const line of failures) console.error(`- ${line}`);
    process.exit(1);
  }

  console.log(`post image validation passed (${targets.length} posts)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
