import fs from 'node:fs/promises';
import path from 'node:path';
import { spawn } from 'node:child_process';
import matter from 'gray-matter';
import { LOG_DIR, POSTS_DIR, ensureDir, loadPostsFrontmatter } from './utils';

const OUT_DIR = path.join(process.cwd(), 'public/assets/posts');
const PROMPT_PATH = path.join(LOG_DIR, 'post-image-prompts.json');
const IMAGES_PER_POST = Number(process.env.IMAGES_PER_POST ?? '3');

type PromptItem = {
  id: string;
  prompt: string;
  size: string;
};

function todayKST() {
  const now = new Date();
  const kst = new Date(now.getTime() + 9 * 60 * 60 * 1000);
  return `${kst.getUTCFullYear()}-${String(kst.getUTCMonth() + 1).padStart(2, '0')}-${String(kst.getUTCDate()).padStart(2, '0')}`;
}

function imageLine(slug: string, index: number, title: string) {
  return `![${title} 관련 이미지 ${index}](/assets/posts/${slug}-${index}.png)`;
}

function hasPostImage(content: string, slug: string, index: number) {
  return content.includes(`/assets/posts/${slug}-${index}.png`);
}

function buildPrompt(title: string, description: string, index: number) {
  const scene =
    index === 1
      ? '기사 리드 문단에 어울리는 핵심 장면'
      : index === 2
        ? '중간 본문 설명에 어울리는 실무 장면'
        : '후반 요약/FAQ에 어울리는 정돈된 장면';
  return [
    `한국어 정보 기사용 고품질 일러스트를 생성한다.`,
    `주제: ${title}`,
    `요약: ${description}`,
    `장면: ${scene}`,
    `스타일: 차분한 뉴스/매거진 톤, 사실적 구도, 텍스트/로고/워터마크 절대 금지, 배너/광고 문구 금지.`,
    `인물 표정 과장 금지, 손/사물 비율 자연스럽게, 깔끔한 색감, 16:9 가로 이미지.`
  ].join('\n');
}

function insertImages(content: string, slug: string, title: string) {
  let updated = content;
  const missing: number[] = [];

  for (let i = 1; i <= IMAGES_PER_POST; i += 1) {
    if (!hasPostImage(updated, slug, i)) missing.push(i);
  }
  if (!missing.length) return updated;

  const firstH2 = updated.search(/^##\s+/m);
  if (firstH2 > 0) {
    const lead = imageLine(slug, missing[0], title);
    updated = `${updated.slice(0, firstH2).trimEnd()}\n\n${lead}\n\n${updated.slice(firstH2)}`;
    missing.shift();
  }

  for (const idx of missing) {
    const h2Match = updated.match(/^##\s+.+$/gm);
    if (h2Match && h2Match.length > 0) {
      const anchor = h2Match[Math.min(idx - 1, h2Match.length - 1)];
      const pos = updated.indexOf(anchor);
      if (pos >= 0) {
        updated = `${updated.slice(0, pos)}${imageLine(slug, idx, title)}\n\n${updated.slice(pos)}`;
        continue;
      }
    }
    updated = `${updated.trimEnd()}\n\n${imageLine(slug, idx, title)}\n`;
  }

  return updated;
}

async function runNodeScript(scriptPath: string, args: string[]) {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(process.execPath, [scriptPath, ...args], {
      cwd: process.cwd(),
      stdio: 'inherit',
      env: process.env
    });
    child.on('error', reject);
    child.on('exit', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`image generator exited with code ${code}`));
    });
  });
}

async function main() {
  await ensureDir(LOG_DIR);
  await ensureDir(POSTS_DIR);
  await ensureDir(OUT_DIR);

  const posts = await loadPostsFrontmatter();
  const today = todayKST();
  const targets = posts.filter((row) => row.data.autoGenerated === true && row.data.publishedAt === today);

  if (targets.length === 0) {
    console.log('no target posts for image generation');
    return;
  }

  const prompts: PromptItem[] = [];
  for (const row of targets) {
    const slug = String(row.data.slug ?? '');
    const title = String(row.data.title ?? '').trim();
    const description = String(row.data.description ?? '').trim();
    if (!slug || !title) continue;
    for (let i = 1; i <= IMAGES_PER_POST; i += 1) {
      prompts.push({
        id: `${slug}-${i}`,
        prompt: buildPrompt(title, description, i),
        size: '1536x1024'
      });
    }
  }

  await fs.writeFile(PROMPT_PATH, JSON.stringify(prompts, null, 2), 'utf8');
  await runNodeScript(path.join(process.cwd(), 'scripts/generate-nanobanana-images.mjs'), [PROMPT_PATH, OUT_DIR]);

  for (const row of targets) {
    const slug = String(row.data.slug ?? '');
    const title = String(row.data.title ?? '').trim();
    if (!slug || !title) continue;
    const parsed = matter(row.body);
    const nextContent = insertImages(parsed.content, slug, title);
    if (nextContent === parsed.content) continue;
    const updatedDoc = matter.stringify(nextContent, parsed.data);
    await fs.writeFile(row.file, updatedDoc, 'utf8');
  }

  console.log(`generated and attached images: posts=${targets.length}, perPost=${IMAGES_PER_POST}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
