import fs from 'node:fs/promises';
import path from 'node:path';
import matter from 'gray-matter';
import OpenAI from 'openai';
import { isUnsafeTopic, shouldAddDisclaimer } from './policy';
import {
  LOG_DIR,
  POSTS_DIR,
  ensureDir,
  jaccardSimilarity,
  loadPostsFrontmatter,
  slugify,
  wordCount
} from './utils';

const todayPath = path.join(process.cwd(), 'src/content/keywords/today.json');
const forbiddenPath = path.join(process.cwd(), 'src/content/keywords/forbidden.txt');

function todayKST() {
  const now = new Date();
  const kst = new Date(now.getTime() + 9 * 60 * 60 * 1000);
  return `${kst.getUTCFullYear()}-${String(kst.getUTCMonth() + 1).padStart(2, '0')}-${String(kst.getUTCDate()).padStart(2, '0')}`;
}

async function readForbidden() {
  const raw = await fs.readFile(forbiddenPath, 'utf8');
  return raw
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);
}

function countH2(content: string) {
  return (content.match(/^##\s+/gm) ?? []).length;
}

function countFaqItems(content: string) {
  const faq = content.match(/##\s*FAQ[\s\S]*$/i)?.[0] ?? '';
  return (faq.match(/Q\d|^\s*-\s*Q[:.]|^\s*\*\*Q/gi) ?? []).length;
}

function validateDraft(
  markdown: string,
  forbidden: string[],
  baseSlug: string,
  existingTitles: string[],
  existingSlugs: Set<string>
) {
  let parsed: matter.GrayMatterFile<string>;
  try {
    parsed = matter(markdown);
  } catch {
    return { ok: false as const, reason: 'invalid frontmatter' };
  }

  const title = String(parsed.data.title ?? '').trim();
  const description = String(parsed.data.description ?? '').trim();
  const tags = Array.isArray(parsed.data.tags) ? parsed.data.tags.map(String) : [];
  const category = String(parsed.data.category ?? '').trim();
  const readingTime = Number(parsed.data.readingTimeMinutes ?? 0);
  const slug = slugify(String(parsed.data.slug ?? baseSlug)) || baseSlug;
  const content = parsed.content;

  if (!title || !description || !tags.length || !category || !Number.isFinite(readingTime) || readingTime <= 0) {
    return { ok: false as const, reason: 'missing required frontmatter fields' };
  }

  if (wordCount(content) < 1200) {
    return { ok: false as const, reason: 'word count < 1200' };
  }
  if (countH2(content) < 4) {
    return { ok: false as const, reason: 'h2 count < 4' };
  }
  if (countFaqItems(content) < 3) {
    return { ok: false as const, reason: 'faq count < 3' };
  }
  if (!/업데이트:\s*\d{4}-\d{2}-\d{2}/.test(content)) {
    return { ok: false as const, reason: 'missing update line' };
  }
  if (!content.includes('<!-- RELATED_POSTS -->')) {
    return { ok: false as const, reason: 'missing related placeholder' };
  }
  if (/(AI가|인공지능이|생성형\s*AI|GPT|ChatGPT)/i.test(content)) {
    return { ok: false as const, reason: 'mentions AI generation' };
  }

  const hitForbidden = forbidden.find((word) => `${title}\n${content}`.includes(word));
  if (hitForbidden) {
    return { ok: false as const, reason: `forbidden word: ${hitForbidden}` };
  }

  const similarity = Math.max(...existingTitles.map((t) => jaccardSimilarity(t, title)), 0);
  if (similarity >= 0.7 || existingSlugs.has(slug)) {
    return { ok: false as const, reason: `duplicate similarity/slug (${similarity.toFixed(2)})` };
  }

  return { ok: true as const, parsed, slug, title };
}

async function main() {
  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) throw new Error('OPENAI_API_KEY is required');

  await ensureDir(POSTS_DIR);
  await ensureDir(LOG_DIR);

  const rawKeywords = JSON.parse(await fs.readFile(todayPath, 'utf8')) as { keywords: string[] };
  const count = Number(process.env.ARTICLE_COUNT ?? '10');
  const forbidden = await readForbidden();

  const existing = await loadPostsFrontmatter();
  const existingTitles = existing.map((row) => String(row.data.title ?? ''));
  const existingSlugs = new Set(existing.map((row) => String(row.data.slug ?? '')));

  const client = new OpenAI({ apiKey });
  const created: string[] = [];
  const logLines: string[] = [];

  for (const keyword of rawKeywords.keywords.slice(0, count)) {
    if (isUnsafeTopic(keyword)) {
      logLines.push(`skip unsafe keyword: ${keyword}`);
      continue;
    }

    const baseSlug = slugify(keyword);
    if (!baseSlug || existingSlugs.has(baseSlug)) {
      logLines.push(`skip duplicate slug keyword: ${keyword}`);
      continue;
    }

    const basePrompt = [
      '한국어 정보형 블로그 글을 Markdown으로 작성하라.',
      `키워드: ${keyword}`,
      '필수 frontmatter: title, description, slug, publishedAt, updatedAt, tags, category, readingTimeMinutes, autoGenerated.',
      `publishedAt/updatedAt는 ${todayKST()}로 작성.`,
      '본문 규칙: 도입 1개, H2 4~6개(필수), H3 선택, FAQ 섹션에서 Q&A 3개 포함.',
      '최소 1200단어 이상.',
      '문체: 중립적, 과장 금지, 확실하지 않은 사실은 "확실하지 않음"이라고 명시.',
      '개인 맞춤 의료/법률/금융 조언 금지.',
      '정량 수치 단정 금지. 출처 불명 수치 금지.',
      '반드시 본문 하단에 "업데이트: YYYY-MM-DD" 한 줄 포함.',
      '본문 마지막에 "<!-- RELATED_POSTS -->" 플레이스홀더를 반드시 포함.',
      'AI 생성 언급 금지.',
      `금지어: ${forbidden.join(', ')}`,
      shouldAddDisclaimer(keyword)
        ? '민감 주제 가능성이 있으므로 면책 문장을 한 단락 포함.'
        : '일반 정보 주제로 작성.'
    ].join('\n');

    let accepted: { parsed: matter.GrayMatterFile<string>; slug: string; title: string } | null = null;
    let lastReason = '';

    for (let attempt = 1; attempt <= 3; attempt += 1) {
      const prompt = attempt === 1 ? basePrompt : `${basePrompt}\n이전 결과 실패 이유: ${lastReason}\n실패 원인을 수정해 다시 작성하라.`;
      const response = await client.responses.create({
        model: process.env.OPENAI_MODEL ?? 'gpt-4.1-mini',
        temperature: 0.7,
        input: prompt
      });

      const markdown = response.output_text?.trim();
      if (!markdown) {
        lastReason = 'empty output';
        continue;
      }

      const result = validateDraft(markdown, forbidden, baseSlug, existingTitles, existingSlugs);
      if (!result.ok) {
        lastReason = result.reason;
        continue;
      }

      accepted = {
        parsed: result.parsed,
        slug: result.slug,
        title: result.title
      };
      break;
    }

    if (!accepted) {
      logLines.push(`skip after retries: ${keyword} (${lastReason || 'unknown'})`);
      continue;
    }

    accepted.parsed.data.slug = accepted.slug;
    accepted.parsed.data.publishedAt = todayKST();
    accepted.parsed.data.updatedAt = todayKST();
    accepted.parsed.data.autoGenerated = true;

    const finalDoc = matter.stringify(accepted.parsed.content, accepted.parsed.data);
    const filePath = path.join(POSTS_DIR, `${accepted.slug}.md`);
    await fs.writeFile(filePath, finalDoc, 'utf8');

    created.push(filePath);
    existingTitles.push(accepted.title);
    existingSlugs.add(accepted.slug);
    logLines.push(`created: ${accepted.slug}`);
  }

  const logPath = path.join(LOG_DIR, `generate-${Date.now()}.log`);
  await fs.writeFile(logPath, logLines.join('\n'), 'utf8');
  console.log(`created articles: ${created.length}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
