import { appendFile, mkdir, readFile, readdir, rename, stat } from 'node:fs/promises';
import { basename, resolve } from 'node:path';
import matter from 'gray-matter';

const root = resolve(import.meta.dirname, '..');
const queueDir = resolve(root, 'content-queue');
const postsDir = resolve(root, 'src/content/posts');
const assetsDir = resolve(root, 'public/assets/posts');
const outputPath = process.env.GITHUB_OUTPUT;

const setOutput = async (key: string, value: string) => {
  if (outputPath) await appendFile(outputPath, `${key}=${value}\n`);
};

await mkdir(queueDir, { recursive: true });
const candidates = (await readdir(queueDir))
  .filter((file) => file.endsWith('.md'))
  .sort((a, b) => a.localeCompare(b, 'ko'));

if (!candidates.length) {
  console.log('승인된 발행 대기 원고가 없습니다.');
  await setOutput('published', 'false');
  process.exit(0);
}

const now = Date.now();
let selected: { file: string; slug: string; imagePaths: string[] } | undefined;

for (const file of candidates) {
  const sourcePath = resolve(queueDir, file);
  const raw = await readFile(sourcePath, 'utf8');
  const parsed = matter(raw);
  const slug = String(parsed.data.slug || '').trim();
  const approved = parsed.data.editorialReview === true;
  const publishAfter = Date.parse(String(parsed.data.publishAfter || parsed.data.publishedAt || ''));
  const plainText = parsed.content
    .replace(/!\[[^\]]*\]\([^)]*\)/g, '')
    .replace(/\[[^\]]+\]\([^)]*\)/g, '$1')
    .replace(/[#>*_`~-]/g, '')
    .replace(/\s+/g, ' ')
    .trim();

  if (!approved || parsed.data.autoGenerated === true) continue;
  if (!slug || !Number.isFinite(publishAfter) || publishAfter > now) continue;
  if (plainText.length < 1800) {
    throw new Error(`${file}: 본문이 1,800자 미만이라 발행할 수 없습니다.`);
  }
  if (!parsed.data.title || !parsed.data.description || !parsed.data.updatedAt) {
    throw new Error(`${file}: 필수 메타데이터가 누락되었습니다.`);
  }
  if (await stat(resolve(postsDir, `${slug}.md`)).catch(() => null)) {
    throw new Error(`${file}: 같은 slug의 게시물이 이미 존재합니다.`);
  }

  const imagePaths = [...parsed.content.matchAll(/\/assets\/posts\/([^\s)"']+)/g)].map((match) => match[1]);
  if (imagePaths.length < 1) throw new Error(`${file}: 본문 이미지가 없습니다.`);
  for (const image of imagePaths) {
    if (!(await stat(resolve(assetsDir, image)).catch(() => null))) {
      throw new Error(`${file}: 이미지 파일이 없습니다: ${image}`);
    }
  }

  selected = { file, slug, imagePaths };
  break;
}

if (!selected) {
  console.log('현재 발행 시각이 된 승인 원고가 없습니다.');
  await setOutput('published', 'false');
  process.exit(0);
}

await mkdir(postsDir, { recursive: true });
await rename(resolve(queueDir, selected.file), resolve(postsDir, `${selected.slug}.md`));
await setOutput('published', 'true');
await setOutput('slug', selected.slug);
console.log(`승인 원고 발행 준비 완료: ${basename(selected.file)} -> ${selected.slug}`);
